# Generated by Django 5.2.4 on 2025-10-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_etudiant_profil_etudiant_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='nom',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
