# Generated by Django 5.2.4 on 2025-10-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_encadreur_telephone_etudiant_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='encadreur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'encadreur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil'),
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='Encadreur',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
