# Generated by Django 5.2.4 on 2025-10-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cours_encadreur_remove_etudiant_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, default='profils/IMG-20250807-WA0097.jpg', null=True, upload_to='profils/'),
        ),
    ]
