# Generated by Django 5.2.4 on 2025-10-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='nom',
            field=models.CharField(choices=[('L0', 'Préparatoire'), ('B1', 'BioMédical1'), ('B2', 'BioMédical2'), ('B3', 'BioMédical3'), ('M1', 'Master1')], default='L0', max_length=50, null=True, unique=True),
        ),
    ]
