# Generated by Django 5.2.4 on 2025-10-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_promotion_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='promotion',
            field=models.CharField(choices=[('L0', 'Préparatoire'), ('B1', 'BioMédical1'), ('B2', 'BioMédical2'), ('B3', 'BioMédical3'), ('M1', 'Master1')], default='L0', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='promotion',
            field=models.CharField(choices=[('L0', 'Préparatoire'), ('B1', 'BioMédical1'), ('B2', 'BioMédical2'), ('B3', 'BioMédical3'), ('M1', 'Master1')], default='L0', max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
