# Generated by Django 5.2.4 on 2025-11-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cours_promotion_alter_profil_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cours_enseignes',
            field=models.ManyToManyField(blank=True, related_name='encadreurs', to='core.cours'),
        ),
    ]
