# Generated by Django 5.2.4 on 2025-11-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profil_cours_enseignes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fichier',
        ),
        migrations.AddField(
            model_name='document',
            name='categorie',
            field=models.CharField(choices=[('notes', 'Notes'), ('items', 'Items'), ('resume', 'Résumé'), ('autre', 'Autre')], default='notes', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='core.document')),
            ],
        ),
    ]
