# Generated by Django 5.2.4 on 2025-11-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_document_fichier_document_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='fichier_pdf',
        ),
    ]
