# Generated by Django 5.2.4 on 2025-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cours_fichier_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('encadreur', 'Encadreur'), ('etudiant', 'Étudiant'), ('coordinateur', 'Coordinateur')], default='etudiant', max_length=20),
        ),
    ]
