# Generated by Django 5.2.4 on 2025-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promotion_cours_promotion_profil_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
