# Generated by Django 5.2.4 on 2025-10-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profil_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='profil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profil'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promotion'),
        ),
    ]
