# Generated by Django 5.2.4 on 2025-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_etudiant_promotion_alter_promotion_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadreur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
