# Generated by Django 5.2.4 on 2025-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profil_promotion_alter_cours_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='promotion',
            field=models.CharField(choices=[('L0', 'Préparatoire'), ('B1', 'BioMédical1'), ('B2', 'BioMédical2'), ('B3', 'BioMédical3'), ('M1', 'Master1')], default='L0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='promotion',
            field=models.CharField(choices=[('L0', 'Préparatoire'), ('B1', 'BioMédical1'), ('B2', 'BioMédical2'), ('B3', 'BioMédical3'), ('M1', 'Master1')], default='L0', max_length=50, null=True),
        ),
    ]
